### ISSUE TITLE
Solr nemá práva k /usr/local/sorl

### ISSUE THREAD

**Issue by rzeh4n** [moravianlibrary/kramerius-docker#9]
Chtěl jsem si rozjet Kramrius v Dockeru, ale zasekl jsem se na tom, že solr nemá práva zápisu do /usr/local/solr/data.
 ```
12-Apr-2016 15:35:13.732 INFO [localhost-startStop-1] org.apache.solr.core.SolrCore.<init> [] Opening new SolrCore at /usr/local/solr/./, dataDir=/usr/local/solr/./data/
12-Apr-2016 15:35:13.734 INFO [localhost-startStop-1] org.apache.solr.core.JmxMonitoredMap.<init> JMX monitoring is enabled. Adding Solr mbeans to JMX Server: com.sun.jmx.mbeanserver.JmxMBeanServer@5c1a1cb1
12-Apr-2016 15:35:13.755 INFO [localhost-startStop-1] org.apache.solr.core.SolrCore.initListeners [] Added SolrEventListener for newSearcher: org.apache.solr.core.QuerySenderListener{queries=[]}
12-Apr-2016 15:35:13.755 INFO [localhost-startStop-1] org.apache.solr.core.SolrCore.initListeners [] Added SolrEventListener for firstSearcher: org.apache.solr.core.QuerySenderListener{queries=[{q=static firstSearcher warming in solrconfig.xml}]}
12-Apr-2016 15:35:13.762 WARNING [localhost-startStop-1] org.apache.solr.core.SolrCore.initIndex [] Solr index directory '/usr/local/solr/./data/index' doesn't exist. Creating new index...
12-Apr-2016 15:35:13.809 SEVERE [localhost-startStop-1] org.apache.solr.common.SolrException.log java.lang.RuntimeException: java.io.IOException: Cannot create directory: /usr/local/solr/./data/index
	at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:409)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:554)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:463)
	at org.apache.solr.core.CoreContainer.load(CoreContainer.java:316)
	at org.apache.solr.core.CoreContainer$Initializer.initialize(CoreContainer.java:133)
	at org.apache.solr.servlet.SolrDispatchFilter.init(SolrDispatchFilter.java:94)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4658)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5277)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot create directory: /usr/local/solr/./data/index
	at org.apache.lucene.store.NativeFSLock.obtain(NativeFSLockFactory.java:171)
	at org.apache.lucene.store.Lock.obtain(Lock.java:72)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1108)
	at org.apache.solr.update.SolrIndexWriter.<init>(SolrIndexWriter.java:83)
	at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:404)
	... 21 more
```
Martin to řešil v 542c21fc51e0d36d7cce1d5c92bff17f9e903481, na Docker Hub je [den stará verze](https://hub.docker.com/r/moravianlibrary/solr/tags/), ale i tak se to chová, jakoby ten proces práva neměl.

**Comment by MartinRumanek** [comment]
Jakou máš prosím verzi Dockeru?

```
$ docker -v
Docker version 1.9.1, build ee06d03/1.9.1
```

**Comment by rzeh4n** [comment]
Docker version 1.10.3, build 20f81dd

**Comment by MartinRumanek** [comment]
To zkoušíš s tímto https://github.com/moravianlibrary/kramerius-docker/blob/master/docker-compose.yml?

Smaž si prosím na svém počítači /data/solr. On ten proces nově neběží pod rootem (to nám zakazuje OpenShift) a pokud máš ten adresář z minulých pokusů tak do toho nedokáže zapisovat.

Kvůli OpenShiftu jsem toho teď předělal více `Source-to-Image`  pro OpenShift (budeme na testu dělat continous delivery) proces, ale dá se to pustit i mimo něj viz https://github.com/moravianlibrary/s2i-kramerius/blob/master/README.md.

**Comment by rzeh4n** [comment]
jo, tohle: https://github.com/moravianlibrary/kramerius-docker/blob/master/docker-compose.yml
Docker daemon/engine mi jede standardne pod rootem, myslel jsem, že používá nějaké systémové věci a ani to jinak nejde. Každopádně vlastník všech volumes je root. 
Když smažu /data/*, tak se mi ta struktura vytvoří znovu, vlastník je root a solr opět spadne na právech k vytvoření adresáře index.

Nakonec stačilo chmod o+w na /data/solr a restartovat. Ale zajímavé, že Fedora si data ukládá v pohodě, všechno pod rootem, a solr ne.
